# Generated by Django 4.1.4 on 2022-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='superuser', max_length=200),
            preserve_default=False,
        ),
    ]
